/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CyrusRouteImport } from './routes/cyrus'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiRawRouteImport } from './routes/api/raw'
import { Route as ApiEventsRouteImport } from './routes/api/events'

const CyrusRoute = CyrusRouteImport.update({
  id: '/cyrus',
  path: '/cyrus',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRawRoute = ApiRawRouteImport.update({
  id: '/api/raw',
  path: '/api/raw',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/cyrus': typeof CyrusRoute
  '/api/events': typeof ApiEventsRoute
  '/api/raw': typeof ApiRawRoute
  '/api/upload': typeof ApiUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/cyrus': typeof CyrusRoute
  '/api/events': typeof ApiEventsRoute
  '/api/raw': typeof ApiRawRoute
  '/api/upload': typeof ApiUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/cyrus': typeof CyrusRoute
  '/api/events': typeof ApiEventsRoute
  '/api/raw': typeof ApiRawRoute
  '/api/upload': typeof ApiUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$' | '/cyrus' | '/api/events' | '/api/raw' | '/api/upload'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$' | '/cyrus' | '/api/events' | '/api/raw' | '/api/upload'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/cyrus'
    | '/api/events'
    | '/api/raw'
    | '/api/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  CyrusRoute: typeof CyrusRoute
  ApiEventsRoute: typeof ApiEventsRoute
  ApiRawRoute: typeof ApiRawRoute
  ApiUploadRoute: typeof ApiUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cyrus': {
      id: '/cyrus'
      path: '/cyrus'
      fullPath: '/cyrus'
      preLoaderRoute: typeof CyrusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/raw': {
      id: '/api/raw'
      path: '/api/raw'
      fullPath: '/api/raw'
      preLoaderRoute: typeof ApiRawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  CyrusRoute: CyrusRoute,
  ApiEventsRoute: ApiEventsRoute,
  ApiRawRoute: ApiRawRoute,
  ApiUploadRoute: ApiUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
